name: Deploy Docker Application over SSH

on:
  workflow_dispatch:
    inputs:
      server:
        description: Hostname of server to deploy to
        required: true
        type: string
      version:
        description: Release version of appliction
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      # - name: Pull docker tar archive from github release
      #   run: wget https://github.com/jesswonky/github-actions-test/releases/download/${{ inputs.version }}/test-application-docker-export.tar

      # - name: Send docker tar archive to remote server via ssh

      # - name: Import tar archive into docker 

      # - name: testing
      #   run: echo  The tags are $SERVER with $VERSION
      #   env:
      #     SERVER: ${{ inputs.server }}
      #     VERSION: ${{ inputs.version }}

      - name: make ansible inventory script executable
        run: chmod +x ansible/inventory/github-env.py

      - name: ansible test
        run: ansible-playbook -i inventory deploy.yaml
        working-directory: ./ansible
        env:
          SERVER: ${{ inputs.server }}
          VERSION: ${{ inputs.version }}
