name: Build Test Application Docker Image

on:
  push:
    #paths: [ 'application' ]
#     branches: [ 'releases/**' ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    #paths: [ 'application' ]
#     branches: [ 'releases/**' ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build application --tag test-application

    - name: Save Docker image to tar
      run: |
        mkdir build
        docker save -o build/test-application-docker-export.tar test-application
        
  release:
  
    runs-on: ubuntu-latest
    
    needs: [build]
    
    steps:

#     - name: Create Github Release
#       uses: fnkr/github-action-ghr@v1
#       #if: startsWith(github.ref, 'refs/tags/')
#       env:
#         GHR_COMPRESS: gz
#         GHR_PATH: build/test-application-docker-export.tar
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub release
      uses: Roang-zero1/github-create-release-action@v3
      with:
        version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload release artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@v3
      with:
        args: "build/test-application-docker-export.tar"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
