name: Build Test Application Docker Image

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build application --tag test-application:${{ github.ref_name }}

    - name: debug
      run: docker images

    - name: Save Docker image to tar
      run: |
        mkdir build
        docker save -o build/test-application-docker-export.tar test-application:${{ github.ref_name }}
        
    - name: Create GitHub release
      uses: Roang-zero1/github-create-release-action@v3
      with:
        version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload release artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@v3
      with:
        args: "build/test-application-docker-export.tar"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
